# Generated by Django 3.2.4 on 2021-07-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('long_long_long_long_long_char_field', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text_field', models.TextField(blank=True, default=None, null=True)),
                ('number_field', models.IntegerField(blank=True, default=None, null=True)),
                ('url_field', models.URLField(default=None, max_length=500, null=True)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tagmodel')),
            ],
        ),
    ]
